/**
 * lib/emergency.ts — Ambulance numbers directory (all countries).
 * Source: public emergency-number directories (Wikipedia "List of emergency
 * telephone numbers"). One number per country — ambulance only (MVP scope).
 * Mobile browsers open the dialer via tel: links automatically.
 */

export interface AmbulanceEntry {
  country: string;
  flag: string;
  number: string;
  note?: string;
}

export const AMBULANCE_NUMBERS: AmbulanceEntry[] = [
  { country: "Pakistan", flag: "🇵🇰", number: "1122", note: "Rescue 1122 · Edhi 115" },
  { country: "India", flag: "🇮🇳", number: "108", note: "Also 102 (mother & child)" },
  { country: "United States", flag: "🇺🇸", number: "911" },
  { country: "United Kingdom", flag: "🇬🇧", number: "999", note: "112 also works" },
  { country: "Canada", flag: "🇨🇦", number: "911" },
  { country: "Australia", flag: "🇦🇺", number: "000" },
  { country: "New Zealand", flag: "🇳🇿", number: "111" },
  { country: "Ireland", flag: "🇮🇪", number: "112", note: "999 also works" },
  { country: "Germany", flag: "🇩🇪", number: "112" },
  { country: "France", flag: "🇫🇷", number: "15", note: "SAMU · 112 universal" },
  { country: "Italy", flag: "🇮🇹", number: "118" },
  { country: "Spain", flag: "🇪🇸", number: "112" },
  { country: "Portugal", flag: "🇵🇹", number: "112" },
  { country: "Netherlands", flag: "🇳🇱", number: "112" },
  { country: "Belgium", flag: "🇧🇪", number: "100" },
  { country: "Switzerland", flag: "🇨🇭", number: "144" },
  { country: "Austria", flag: "🇦🇹", number: "144" },
  { country: "Sweden", flag: "🇸🇪", number: "112" },
  { country: "Norway", flag: "🇳🇴", number: "113" },
  { country: "Denmark", flag: "🇩🇰", number: "112" },
  { country: "Finland", flag: "🇫🇮", number: "112" },
  { country: "Iceland", flag: "🇮🇸", number: "112" },
  { country: "Poland", flag: "🇵🇱", number: "999" },
  { country: "Czech Republic", flag: "🇨🇿", number: "155" },
  { country: "Slovakia", flag: "🇸🇰", number: "155" },
  { country: "Hungary", flag: "🇭🇺", number: "104" },
  { country: "Romania", flag: "🇷🇴", number: "112" },
  { country: "Bulgaria", flag: "🇧🇬", number: "150" },
  { country: "Greece", flag: "🇬🇷", number: "166" },
  { country: "Turkey", flag: "🇹🇷", number: "112" },
  { country: "Russia", flag: "🇷🇺", number: "103" },
  { country: "Ukraine", flag: "🇺🇦", number: "103" },
  { country: "Belarus", flag: "🇧🇾", number: "103" },
  { country: "Moldova", flag: "🇲🇩", number: "903" },
  { country: "Estonia", flag: "🇪🇪", number: "112" },
  { country: "Latvia", flag: "🇱🇻", number: "113" },
  { country: "Lithuania", flag: "🇱🇹", number: "103" },
  { country: "Serbia", flag: "🇷🇸", number: "194" },
  { country: "Croatia", flag: "🇭🇷", number: "194" },
  { country: "Bosnia & Herzegovina", flag: "🇧🇦", number: "124" },
  { country: "Slovenia", flag: "🇸🇮", number: "112" },
  { country: "Albania", flag: "🇦🇱", number: "127" },
  { country: "North Macedonia", flag: "🇲🇰", number: "194" },
  { country: "Montenegro", flag: "🇲🇪", number: "124" },
  { country: "China", flag: "🇨🇳", number: "120" },
  { country: "Japan", flag: "🇯🇵", number: "119" },
  { country: "South Korea", flag: "🇰🇷", number: "119" },
  { country: "Taiwan", flag: "🇹🇼", number: "119" },
  { country: "Hong Kong", flag: "🇭🇰", number: "999" },
  { country: "Singapore", flag: "🇸🇬", number: "995" },
  { country: "Malaysia", flag: "🇲🇾", number: "999" },
  { country: "Indonesia", flag: "🇮🇩", number: "119" },
  { country: "Thailand", flag: "🇹🇭", number: "1669" },
  { country: "Vietnam", flag: "🇻🇳", number: "115" },
  { country: "Philippines", flag: "🇵🇭", number: "911" },
  { country: "Bangladesh", flag: "🇧🇩", number: "999" },
  { country: "Sri Lanka", flag: "🇱🇰", number: "1990", note: "Suwa Seriya ambulance" },
  { country: "Nepal", flag: "🇳🇵", number: "102" },
  { country: "Bhutan", flag: "🇧🇹", number: "112" },
  { country: "Maldives", flag: "🇲🇻", number: "102" },
  { country: "Myanmar", flag: "🇲🇲", number: "192" },
  { country: "Cambodia", flag: "🇰🇭", number: "119" },
  { country: "Laos", flag: "🇱🇦", number: "195" },
  { country: "Mongolia", flag: "🇲🇳", number: "103" },
  { country: "Afghanistan", flag: "🇦🇫", number: "112" },
  { country: "Iran", flag: "🇮🇷", number: "115" },
  { country: "Iraq", flag: "🇮🇶", number: "122" },
  { country: "Saudi Arabia", flag: "🇸🇦", number: "997" },
  { country: "United Arab Emirates", flag: "🇦🇪", number: "998" },
  { country: "Qatar", flag: "🇶🇦", number: "999" },
  { country: "Kuwait", flag: "🇰🇼", number: "777" },
  { country: "Bahrain", flag: "🇧🇭", number: "999" },
  { country: "Oman", flag: "🇴🇲", number: "9999" },
  { country: "Yemen", flag: "🇾🇪", number: "199" },
  { country: "Jordan", flag: "🇯🇴", number: "191" },
  { country: "Lebanon", flag: "🇱🇧", number: "140" },
  { country: "Syria", flag: "🇸🇾", number: "110" },
  { country: "Israel", flag: "🇮🇱", number: "101" },
  { country: "Palestine", flag: "🇵🇸", number: "101" },
  { country: "Egypt", flag: "🇪🇬", number: "123" },
  { country: "Libya", flag: "🇱🇾", number: "193" },
  { country: "Tunisia", flag: "🇹🇳", number: "190" },
  { country: "Algeria", flag: "🇩🇿", number: "14" },
  { country: "Morocco", flag: "🇲🇦", number: "15" },
  { country: "Sudan", flag: "🇸🇩", number: "999" },
  { country: "Ethiopia", flag: "🇪🇹", number: "907", note: "Red Cross" },
  { country: "Kenya", flag: "🇰🇪", number: "999" },
  { country: "Tanzania", flag: "🇹🇿", number: "112" },
  { country: "Uganda", flag: "🇺🇬", number: "999" },
  { country: "Rwanda", flag: "🇷🇼", number: "112" },
  { country: "Nigeria", flag: "🇳🇬", number: "199" },
  { country: "Ghana", flag: "🇬🇭", number: "193" },
  { country: "Senegal", flag: "🇸🇳", number: "1515" },
  { country: "South Africa", flag: "🇿🇦", number: "10177" },
  { country: "Zimbabwe", flag: "🇿🇼", number: "999" },
  { country: "Zambia", flag: "🇿🇲", number: "991" },
  { country: "Mauritius", flag: "🇲🇺", number: "114" },
  { country: "Brazil", flag: "🇧🇷", number: "192", note: "SAMU" },
  { country: "Argentina", flag: "🇦🇷", number: "107" },
  { country: "Chile", flag: "🇨🇱", number: "131" },
  { country: "Colombia", flag: "🇨🇴", number: "125" },
  { country: "Peru", flag: "🇵🇪", number: "106" },
  { country: "Ecuador", flag: "🇪🇨", number: "911" },
  { country: "Venezuela", flag: "🇻🇪", number: "171" },
  { country: "Bolivia", flag: "🇧🇴", number: "118" },
  { country: "Uruguay", flag: "🇺🇾", number: "105" },
  { country: "Paraguay", flag: "🇵🇾", number: "141" },
  { country: "Mexico", flag: "🇲🇽", number: "911" },
  { country: "Costa Rica", flag: "🇨🇷", number: "911" },
  { country: "Panama", flag: "🇵🇦", number: "911" },
  { country: "Cuba", flag: "🇨🇺", number: "104" },
  { country: "Jamaica", flag: "🇯🇲", number: "110" },
  { country: "Kazakhstan", flag: "🇰🇿", number: "103" },
  { country: "Uzbekistan", flag: "🇺🇿", number: "103" },
  { country: "Kyrgyzstan", flag: "🇰🇬", number: "103" },
  { country: "Tajikistan", flag: "🇹🇯", number: "103" },
  { country: "Turkmenistan", flag: "🇹🇲", number: "103" },
  { country: "Azerbaijan", flag: "🇦🇿", number: "103" },
  { country: "Armenia", flag: "🇦🇲", number: "103" },
  { country: "Georgia", flag: "🇬🇪", number: "112" },
  { country: "Cyprus", flag: "🇨🇾", number: "112" },
  { country: "Malta", flag: "🇲🇹", number: "112" },
  { country: "Luxembourg", flag: "🇱🇺", number: "112" },
];

export function findAmbulance(country: string): AmbulanceEntry | undefined {
  const q = country.trim().toLowerCase();
  return AMBULANCE_NUMBERS.find(
    (a) => a.country.toLowerCase() === q || a.country.toLowerCase().includes(q)
  );
}
